name: gestion-academica-frontend
services:
- name: frontend
  source_dir: /
  github:
    repo: YOUR_GITHUB_USERNAME/YOUR_REPO_NAME
    branch: main
  run_command: npm run preview
  build_command: npm run build:prod
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 3000
  routes:
  - path: /
  envs:
  - key: VITE_API_URL
    value: https://your-backend-app.ondigitalocean.app/api
  - key: VITE_APP_NAME
    value: Gestión Académica
  - key: VITE_APP_VERSION
    value: 1.0.0
  - key: VITE_DEV_MODE
    value: false
  - key: VITE_ENABLE_DEVTOOLS
    value: false
  - key: VITE_FRONTEND_URL
    value: ${APP_URL}
